### PR TITLE
AppVeyor for Windows CI

### LINKED ISSUE #47: Run tests on Appveyor to debug rplugin on Windows
After work done on https://github.com/neovim/neovim/pull/7706, https://github.com/neovim/neovim/pull/7734, https://github.com/neovim/neovim/pull/7738, I can't make a simple echo class with an `EchoHello` command work on Windows. The APIs are fine because testing on them directly, bypassing the host and `rplugin/node`,  works on all OS consistently. `:checkhealth` and `:UpdateRemotePlugins` are ok now (on Windows) and I see `rplugin.vim` with `EchoHello` registered from nodejs plugin I made it.

That leaves msgpack and the `RPC` api from both sides which I don't know how to debug/fix yet.
To get more debug info, the tests should run on Appveyor as well. We can reuse the same configuration from neovim repo.

### PR DESCRIPTION
**Pull request by rhysd**
I tried to setup AppVeyor. I wrote an AppVeyor config and a script to download nightly Neovim package. Now tests look to be run correctly.

But I have seen some test failures for node-host.

~~Since I'm not an node-host user, I could not fix the failures. Can anyone help me?~~

It seems that Travis CI is also failing. I think this is a problem of Neovim nightly and node-host. So I think this PR is mergable. @billyvg, what do you think?

CC: @janlazo

Fixes #47

### CODE REVIEW

**Comment by rhysd** [comment]
I removed `[WIP]` from title because of following.

> It seems that Travis CI is also failing. I think this is a problem of Neovim nightly and node-host. So I think this PR is mergable.

**Comment by rhysd** [comment]
I guess CI on latest master branch is also broken now (last build was 8 days ago, and it passed, tho)

**Comment by janlazo** [comment]
https://github.com/neovim/neovim/blob/master/runtime/autoload/provider/node.vim has breaking changes for the host to support debugging on Windows. `neovim-node-host`is ignored in favor of $(npm root -g)/neovim/bin/cli.js`

**Comment by janlazo** [comment]
try `set shellslash` before getcwd() for the working directory test.

**Comment by janlazo** [comment]
Is `__tests__/integration/autoload/provider/node.vim` deprecated now?

**Comment by rhysd** [comment]
Thank you for your advices. Let me visit this PR again after #50 is merged.

> Is __tests__/integration/autoload/provider/node.vim deprecated now?

I'm not node-host user, so I have no idea. @billyvg, what do you think?

**Comment by rhysd** [comment]
@billyvg @janlazo Now tests run on AppVeyor are passing :+1:

**Comment by janlazo** [comment]
I can run a rplugin on Windows if compiling from source.
After merging this, I want a new release so I can test on neovim HEAD.

**Comment by janlazo** [comment]
In the README, it's useful to mention the minimum node version supported on all OS.
neovim HEAD tests the node host with [nvm lts](https://github.com/neovim/neovim/commit/be53c209c0e0ccff0053fac82f2d8e1c9a40427f#diff-4c4e2c49a21515e6caaaa9786641d761R49) (v6.12.x). I didn't know how to do in Appveyor so I used v8.x.x but v6.12.x works too.

**Comment by rhysd** [comment]
Yes, it should work with v6, but not work with v4. This is because TypeScript compiler compiles codes into ES2015 JavaScript, but v4 does not fully support ES2015.

I feel the latest (v9) and most recent LTS (currently v8) should be tested because they are most popular packages Node.js users are using. I changed AppVeyor config to run tests for both version 8 and the latest.

**Comment by billyvg** [comment]
Yeah I believe `__tests__/integration/autoload/provider/node.vim` is deprecated now.

**Comment by rhysd** [comment]
@billyvg Thank you for your review 👍

**Pull request merged**
