### PR TITLE
build(lerna): Use lerna and azure devops

### PR DESCRIPTION
**Pull request by billyvg**
Refactor to use lerna + upgrade dev packages (e.g. jest + babel)

### CODE REVIEW

**Comment by billyvg** [comment]
I did a lot of extra stuff on top of your lerna changes @mhartington 	 :<

**Comment by mhartington** [comment]
🎉 Woot! Will review everything later today. Sorry I wasn't able to complete this. Life got in the way sadly

**Comment by billyvg** [comment]
np, it happens :)

**Comment by billyvg** [comment]
@mhartington 	Given that it's *not* extracted out of `neovim` package, does it need a major bump?

**Comment by mhartington** [comment]
Yeah, if the decorators API is still shipped, I think it could avoid a major version bump and then plan to remove them from core later in time.

**Pull request merged**
