### PR TITLE
Add Buffer to global scope in sandbox

### LINKED ISSUE #141: Node 12 support
This is basically https://github.com/neovim/node-client/issues/122 but with reproduction steps.

Using one of the examples, but with `console.log(Buffer)` line in a command:

```bash
$ mkdir -p /tmp/test/rplugin/node/test

$ cat > /tmp/test/rplugin/node/test/index.js <<EOF
class MyPlugin {
  constructor(plugin) {
    this.plugin = plugin;

    plugin.registerCommand('SetMyLine', [this, this.setLine]);
  }

  setLine() {
    console.log(Buffer)
    this.plugin.nvim.setLine('A line, for your troubles');
  }
}

module.exports = (plugin) => new MyPlugin(plugin);

// Or for convenience, exporting the class itself is equivalent to the above

module.exports = MyPlugin;
EOF
```

On node 10 this works as expected and buffer updated with a line, on node 12 nothing happens and log contains:

```
Error in plugin for command:SetMyLine: Buffer is not defined (file: /tmp/test/rplugin/node/test, stack: ReferenceError: Buffer is not defined
  at MyPlugin.setLine (/tmp/test/rplugin/node/test/index.js:9:17)
  at Object.fn (/home/konstantin/.config/yarn/global/node_modules/neovim/lib/host/NvimPlugin.js:19:26)
  at NvimPlugin.<anonymous> (/home/konstantin/.config/yarn/global/node_modules/neovim/lib/host/NvimPlugin.js:156:41)
  at Generator.next (<anonymous>)
  at /home/konstantin/.config/yarn/global/node_modules/neovim/lib/host/NvimPlugin.js:8:71
  at new Promise (<anonymous>)
  at __awaiter (/home/konstantin/.config/yarn/global/node_modules/neovim/lib/host/NvimPlugin.js:4:12)
  at NvimPlugin.handleRequest (/home/konstantin/.config/yarn/global/node_modules/neovim/lib/host/NvimPlugin.js:134:16)
  at Host.<anonymous> (/home/konstantin/.config/yarn/global/node_modules/neovim/lib/host/index.js:71:27)
  at Generator.next (<anonymous>))
```

### PR DESCRIPTION
**Pull request by rhysd**
Fixes #141

### CODE REVIEW

**Comment by rhysd** [comment]
I noticed this does not work. For example, `Array` is set by sandbox context so for example `[] instanceof Array` is `false`.

**Comment by rhysd** [comment]
According to https://github.com/nodejs/node/blob/master/lib/internal/bootstrap/pre_execution.js, only `process` and `Buffer` are defined in `global`. So I simply added `Buffer` to sandbox context.

**Comment by rhysd** [comment]
Thanks for reviews. Merging.

**Comment by romgrk** [comment]
Do you have an ETA when this will be published to npm? If it could be published soon it would solve an issue with one of my plugins, thanks :) (ping @billyvg)

**Comment by billyvg** [comment]
@romgrk sorry about that, I've released 4.9.0

**Comment by romgrk** [comment]
Thanks :D

**Pull request merged**
